import competition_script as cp
from datetime import datetime


all_competitions = []




lång_sm_2023 = cp.Competition("LÅSM23")
lång_sm_2023.date = datetime(2023,8,20)
lång_sm_2023.h18result = [
    "Odin Ek", "Wilmer Selin", "Ludwig Rosén", "Anton Jonsson", "Svante Selin",
    "Noah Krikström", "Casper Blakskjær", "Linus Forsberg", "Niels Dalgaard",
    "Isak Eskilsson", "Axel Bratt", "Hannes Mogensen", "Max Österberg",
    "Elis Peterson", "Måns Bergqvist", "Olov Norin", "Victor Hörnquist",
    "Elia Kämpe", "Arvid Algers Omholt", "Alfred Kjellén", "Hjalmar Axelsson",
    "Joel Wallner", "Hugo Sjölander", "Oliver Håkansson", "Adam Sjööarv",
    "Ian Johansson", "Wille Söderqvist", "Niklas Erlandsson", "Jonatan Anderson",
    "Tim Lundberg", "Erik Palm", "Mattias Larsson", "Nils Swartz", "Oliver Liwång",
    "Felix Johnsson", "Carl Öberg", "Ted Johnsson", "Olof Arevång", "Linus Nilsson",
    "Alfred Jeppsson", "Isak Skoglund"
]

lång_sm_2023.h20result = [
    "Olle Karlsson",
    "Lukas Larsson",
    "Casper Skepp",
    "Hugo Kindborn",
    "Edvin Nilsson",
    "Marcus Stenebo",
    "Viktor Sone",
    "William Sturesson",
    "Loke Hedberg",
    "Albin Weiden",
    "Gunnar Fovaeus",
    "Hugo Ericsson",
    "Albin Warvelin",
    "Henrik Lundfors",
    "Sverre Röjgård",
    "Teo Struck",
    "Hugo Larsson",
    "Hugo Unosson",
    "Arvid Skepp",
    "Edvin Forsberg",
    "Arvid Björk",
    "Linus Wernström",
    "Willy Fjällborg",
    "Melker Åkesson",
    "Edvin Selin",
    "Oscar David Broman Jensen",
    "Joel Golsäter",
    "Hugo Örn",
    "Sixten Slagbrand",
    "Isak Fransson",
    "Leo Alvolin",
    "David Morén",
    "Esbjörn Montelius Risberg",
    "Aron Hellgren",
    "Erik Bovallius",
    "Ludvig Hedström"
]

lång_sm_2023.h21result = [
    "Viktor Svensk",
    "Jerker Lysell",
    "Martin Regborn",
    "Joakim Svensk",
    "Jens Rönnols",
    "Simon Hector",
    "Ruslan Glebov",
    "Erik Hannrup",
    "Jonatan Gustafsson",
    "Simon Imark",
    "Jesper Svensk",
    "Olle Kalered",
    "Emil Granqvist",
    "Filip Dahlgren",
    "Daniel Roos",
    "Johan Ek-Larsson",
    "Anton Johansson",
    "Filip Ossiansson",
    "Simon Jakobsson",
    "Filip Grahn",
    "Viktor Larsson",
    "August Mollén",
    "Benjamin Näslund",
    "Filip Trofast",
    "Jonas Egger",
    "Oskar Edvardsson",
    "Gustav Hindér",
    "Jesper Sjöblom",
    "Emil Svensk",
    "Gustav Runefors",
    "Hugo Lillieström",
    "Fredrik Glännefors",
    "Gustav Bergman",
    "Oskar Sandberg",
    "Linus Agervig Kristiansson",
    "Simon Harden",
    "Ludvig Åhlund",
    "Simon Schuster"
]

lång_sm_2023.d18result = [
    "Freja Hjerne",
    "Tilia Olsson",
    "Alva Björk",
    "Stina Thern",
    "Ellen Wångberg Aneland",
    "Yrsa Röjgård",
    "Tuva Sirviö",
    "Julia Forsgren",
    "Elise Magnusson",
    "Tuva Östangård",
    "Cajsa Alenius",
    "Lisa Östensson",
    "Alice Ljungberg",
    "Tova Rangert",
    "Sara Ohlin",
    "Sandra Ling",
    "Amanda Cliffordson",
    "Elsa Kaipe",
    "Liv Pauler",
    "Filippa Hjerne",
    "Malva Arvidsson",
    "Sigrid Ljunggren",
    "Lovisa Borg",
    "Sofie Ettling",
    "Emma Hasselström",
    "Signe Hördegårdh",
    "Annie Lund",
    "Tuva Selin",
    "Ella Pettersson",
    "Emma Henriques",
    "Emma Zettervall",
    "Silje Ringstad",
    "Tilda Sundkvist",
    "Alice Rytterstedt",
    "Malin Strömqvist",
    "Tyra Larsson",
    "Saga Rydberg",
    "Maja Axelsson",
    "Hedda Rosengren Svensson"
]

lång_sm_2023.d20result = [
    "Sabina Aumo",
    "Eleonora Alinder",
    "Alma Svennerud",
    "Hanna Jonsell",
    "Boglarka Czakó",
    "Ida Österberg",
    "Elsa Sonesson",
    "Emma Emilsson",
    "Ida Eskilsson",
    "Fredrika Nordquist",
    "Alice Ek",
    "Ebba Thern",
    "Vendela Söderqvist",
    "Erika Åkesson",
    "Nora Westerlund",
    "Amanda Granqvist",
    "Doris Iko",
    "Karin Lindgren",
    "Evelina Svensson Finndahl",
    "Emma Almgren",
    "Flora Aigmüller",
    "Maja Ahlström",
    "Olga Rindeskog",
    "Alice Olvegård",
    "Tindra Jonsson",
    "Vendela Rundström",
    "Astrid White",
    "Ellen Pelander",
    "Elin Ladänges",
    "Matilda Aasa",
    "Emma Westerlund",
    "Olha Sereda",
    "Linnea Solvang Stagg",
    "Hanna Larsson"
]

lång_sm_2023.d21result = [
    "Tove Alexandersson",
    "Marie Olaussen",
    "Veronika Kalinina",
    "Hanna Lundberg",
    "Tilde Backlund",
    "Frida Vikström",
    "Malin Agervig Kristiansson",
    "Evelina Wickbom",
    "Lovisa Persson",
    "Erica Edman",
    "Josefin Tjernlund",
    "Matilda Eriksson",
    "Johanna Källvik Leufvén",
    "Johanna Börjesson Eriksson",
    "Ellinor Tjernlund",
    "Helena Bergman",
    "Rebecka Heinrup",
    "Susen Lösch",
    "Ida Hylander",
    "Louise Lundgren",
    "Fanny Sundblad",
    "Eef Van Dongen",
    "Hanna Hänström",
    "Klara Axelsson",
    "Lisa Holer",
    "Hilda Holmqvist Johansson",
    "Erika Källvik Leufvén",
    "Rebecka Lindberg",
    "Amanda Holmgren",
    "Annick Meister",
    "Irina Nyberg",
    "Jennie Börjesson Eriksson"
]








medel_sm_2023 = cp.Competition("MESM23")
medel_sm_2023.date = datetime(2023,8,26)
medel_sm_2023.h18result = [
        "Hannes Mogensen", "Svante Selin", "Isak Eskilsson", "Max Österberg",
        "Noah Krikström", "Elis Peterson", "Wilmer Selin", "Hannes Persson",
        "Victor Hörnquist", "Arvid Jonforsen", "Jonatan Anderson", "Oliver Håkansson",
        "Ludwig Rosén", "Linus Forsberg", "Felix Johnsson", "Adam Sjööarv",
        "Elmin Hovmöller", "Hugo Sjölander", "Isak Skoglund", "Hampus Sundberg",
        "Alfred Kjellén", "Jonas Sölva", "Arvid Algers Omholt", "Tim Lundberg",
        "Erik Lundquist", "Elias Westerbergh", "Vidar Nettelmark", "Love Bylund",
        "Niklas Erlandsson", "Oliver Liwång", "Emil Åberg", "Jacob Påledal",
        "Viggo Holmberg", "Arvid Myrberger", "Johan Eriksson", "Axel Rydgren",
        "Hannes Lindqvist", "Rasmus Lundström", "Axel Bratt", "Gustav Hellgren"]

medel_sm_2023.h20result = [
    "Noel Braun",
    "Edvin Hellsten",
    "Joel Golsäter",
    "Olle Karlsson",
    "Henrik Lundfors",
    "Linus Wernström",
    "Loke Hedberg",
    "Gunnar Fovaeus",
    "David Morén",
    "Viktor Gunnarsson",
    "Mattias Öhlund",
    "Viktor Sone",
    "Casper Skepp",
    "Hugo Kindborn",
    "Marcus Stenebo",
    "Lukas Larsson",
    "Oskar Vikström",
    "Jesper Åkesson",
    "William Sturesson",
    "Albin Gezelius",
    "Sverre Röjgård",
    "Hugo Larsson",
    "Albin Warvelin",
    "Hugo Ericsson",
    "Aron Hellgren",
    "Edvin Nilsson",
    "Isak Gelius",
    "Albin Weiden",
    "Teo Struck",
    "Hugo Persson",
    "Edvin Forsberg",
    "Arvid Skepp",
    "Theo Lövdahl",
    "Alfred Hallqvist",
    "Ludvig Hedström",
    "Willy Fjällborg",
    "Kasper Lagerström",
    "Filip Håkansson",
    "Edvin Selin"
]

medel_sm_2023.h21result = [
    "Viktor Svensk",
    "Simon Imark",
    "Anton Johansson",
    "Simon Hector",
    "Joakim Svensk",
    "Martin Regborn",
    "Isac von Krusenstierna",
    "Jesper Svensk",
    "Jerker Lysell",
    "Emil Granqvist",
    "Benjamin Näslund",
    "Johan Ek-Larsson",
    "Filip Ossiansson",
    "Eskil Kinneberg",
    "Erik Hannrup",
    "Erik Herne",
    "Gustav Hindér",
    "Filip Grahn",
    "Rassmus Andersson",
    "Lucas Basset",
    "Anton Forsberg",
    "Max Peter Bejmer",
    "Jonas Gustafsson",
    "Axel Granqvist",
    "Ville Johansson",
    "Simon Harden",
    "Ludvig Ek",
    "Kornelius Kriszat-Løvfald",
    "Rickard Börjesson",
    "Daniel Roos",
    "Ludvig Åhlund",
    "Mark Bogataj",
    "Johan Runesson",
    "Jonatan Gustafsson",
    "Axel Wrådhe",
    "Robbin Kantarp",
    "Hugo Lillieström",
    "Jakob Wahl",
    "Jakob Andersson",
    "Andrey Salin"
]

medel_sm_2023.d18result = [
    "Freja Hjerne",
    "Tilia Olsson",
    "Maja Axelsson",
    "Signe Hördegårdh",
    "Alva Björk",
    "Elsa Hedin",
    "Yrsa Röjgård",
    "Ellen Wångberg Aneland",
    "Elsa Brandt",
    "Elise Magnusson",
    "Tuva Östangård",
    "Tyra Larsson",
    "Filippa Hjerne",
    "Lovisa Borg",
    "Julia Rosén",
    "Tova Rangert",
    "Tuva Selin",
    "Maja Lundholm",
    "Julia Forsgren",
    "Lisa Östensson",
    "Tilda Sundkvist",
    "Stina Thern",
    "Alice Ljungberg",
    "Hedda Rosengren Svensson",
    "Agnes Johansson",
    "Wilma Reinholdsson",
    "Cajsa Alenius",
    "Alice Rytterstedt",
    "Malva Arvidsson",
    "Sara Ohlin",
    "Wilma Mårtensson",
    "Sofie Ettling",
    "Moa Bergqvist",
    "Silje Ringstad",
    "Alva Karlsson",
    "Emily Kruys",
    "Sanna Hörnell"
]
medel_sm_2023.d20result = [
    "Sabina Aumo",
    "Alma Svennerud",
    "Pia Young Vik",
    "Klara Borg",
    "Emma Emilsson",
    "Ida Bengtsson",
    "Vendela Söderqvist",
    "Amanda Granqvist",
    "Smilla Mogensen",
    "Erika Åkesson",
    "Lisa Åkesson",
    "Kristin Melby Jacobsen",
    "Elsa Sonesson",
    "Agnes Djurstedt",
    "Ida Österberg",
    "Emma Almgren",
    "Eleonora Alinder",
    "Nora Westerlund",
    "Boglarka Czakó",
    "Sigrid Carlsson",
    "Ebba Thern",
    "Vendela Rundström",
    "Alice Olvegård",
    "Tindra Jonsson",
    "Doris Iko",
    "Emmy Palm",
    "Emma Rindstig",
    "Olga Rindeskog",
    "Elina Reinholdsson",
    "Ebba Näsman",
    "Matilda Aasa",
    "Alicia Bergkvist",
    "Karolina Bergh Papasikas",
    "Cornelia Kindlund",
    "Emma Westerlund",
    "Astrid White"
]

medel_sm_2023.d21result = [
    "Tove Alexandersson",
    "Sara Hagström",
    "Johanna Ridefelt",
    "Veronika Kalinina",
    "Lisa Risby",
    "Andrea Svensson",
    "Josefin Tjernlund",
    "Hanna Lundberg",
    "Marie Olaussen",
    "Lina Strand",
    "Tilda Johansson",
    "Emma Eriksson",
    "Ingrid Lundanes",
    "Tilde Backlund",
    "Ida Lindkvist",
    "Alice Hugosson",
    "Ida Hylander",
    "Elin Månsson",
    "Victoria Hæstad Bjørnstad",
    "Johanna Källvik Leufvén",
    "Olivia Nilsson",
    "Frida Vikström",
    "Hanna Hugosson",
    "Line Cederberg",
    "Rebecka Heinrup",
    "Laura King",
    "Elin Carlsson",
    "Lena Eliasson-Lööf",
    "Erica Edman",
    "Lovisa Persson",
    "Alva Sonesson",
    "Johanna Börjesson Eriksson",
    "Johanna Engström",
    "Lisa Holer",
    "Jannie Hagård",
    "Moa Leijon Lind",
    "Rebecka Lindberg",
    "Emma Helmersson",
    "Fanny Asketun",
    "Ella Sjöberg"
]


sl_1_2023 = cp.Competition("#1SL23")
sl_1_2023.date = datetime(2023, 4,15)
sl_1_2023.h18result = [
    "Hannes Mogensen",
    "Ludwig Rosén",
    "Wilmer Selin",
    "Isak Eskilsson",
    "Oliver Håkansson",
    "Odin Ek",
    "Ola Leire",
    "Max Österberg",
    "Casper Blakskjær",
    "Arvid Jonforsen",
    "Niels Dalgaard",
    "Hannes Persson",
    "Elis Peterson",
    "Axel Bratt",
    "Elia Kämpe",
    "Hannes Lindqvist",
    "Noah Krikström",
    "Anton Jonsson",
    "Linus Forsberg",
    "Emil Åberg",
    "Gustav Hellgren",
    "Olov Norin",
    "Jonatan Anderson",
    "Love Bylund",
    "Vidar Nettelmark",
    "Otto Timby",
    "Adam Sjööarv",
    "Jacob Påledal",
    "Elias Ljungdell",
    "Marcus Lamm",
    "Ludvig Hasler",
    "Linus Nilsson",
    "Arvid Algers Omholt",
    "Tim Martner",
    "Albin Sundström",
    "Joel Wallner",
    "Niklas Erlandsson",
    "Nils Swartz",
    "Viggo Holmberg",
    "Felix Johnsson",
    "Alfred Jeppsson",
    "Elias Westerbergh",
    "Viktor Wistrand",
    "Erik Palm",
    "Alfred Kjellén",
    "Carl Öberg",
    "William Oksvold",
    "Marcus Grunder",
    "Elmin Hovmöller",
    "Ian Johansson",
    "Axel Hejdenberg",
    "Wille Söderqvist",
    "Viggo Wulff",
    "Felix Johansson",
    "Filip Gummesson",
    "Otto Nilsson",
    "Jens Fochsen",
    "Harry Liderfelt",
    "Axel Rydgren",
    "Mattias Larsson",
    "Wilhelm Karmetun",
    "Erik Norin",
    "Ludvig Eronn",
    "Eddie Karlsson",
    "Erik Månsson",
    "Albin Skott",
    "Edvin Halldin",
    "Arvid Eriksson",
    "Axel Trofast",
    "Liam Hogedal",
    "Simon Westh",
    "Hampus Sundberg",
    "Noa Helgars",
    "Jakob Bogsjö Jensen", 
    "Emil Albinsson"
]
   
sl_1_2023.h20result = [
    'William Sturesson',
    'Linus Wernström',
    'Gunnar Fovaeus',
    'Arvid Skepp',
    'Lukas Larsson',
    'Hugo Unosson',
    'Albin Gezelius',
    'Edvin Forsberg',
    'Casper Skepp',
    'Henrik Lundfors',
    'Marcus Stenebo',
    'Jesper Åkesson',
    'Hugo Kindborn',
    'Hugo Larsson',
    'Joel Golsäter',
    'Edvin Hellsten',
    'Albin Weiden',
    'Sverre Röjgård',
    'Isak Lundholm',
    'Mattias Öhlund',
    'Hugo Persson',
    'Elias Nordberg',
    'Leo Alvolin',
    'Mathias Barros-vallet',
    'Theo Lövdahl',
    'Olle Thimberg',
    'Tobias Johansson',
    'Florian Nagel',
    'Sixten Slagbrand',
    'David Morén',
    'Alfred Hallqvist',
    'Hugo Örn',
    'Ludvig Lange',
    'Loke Hedberg',
    'Isak Gelius',
    'Kasper Lagerström',
    'Johan Årbrink',
    'Melker Åkesson',
    'Ludvig Hedström',
    'Anton Kruse',
    'Isak Fransson',
    'John Kinnander',
    'Anders Skoglund',
    'Emil Larsson',
    'Albin Warvelin',
    'Ludvig Karlqvist',
    'Rasmus Lindblom',
    'Edvin Selin',
    'Oskar Ådahl',
    'Erik Bovallius',
    'Joel Holmberg',
    'Esbjörn Montelius Risberg',
    'Teo Struck',
    'Viktor Fröberg',
    'Axel Eveborn',
    'Oscar Wångberg Aneland',
    'Love Persson',
    'Simon Claesson',
    'Noel Helmersson',
    'Simon Bååth',
    'Elis Forsberg Rundström',
    'Hjalmar Olsson',
    'Alfred Johansson',
    'Markus Ljungqvist',
    'Svante Sirviö',
    'Viktor Löfgren',
    'Johan Hansson',
    'Oscar Hultgren',
    'Carl-Henrik Wass',
    'Isak Andersson',
    'Isak Dalin',
    'Hannes Essunger',
    'Mattis Sandén',
    'Alfons Peterson',
    'Eric Johansson'
]

sl_1_2023.h21result = [
    "Gustav Bergman",
    "Anton Johansson",
    "Axel Elmblad",
    "Viktor Svensk",
    "Oskar Sjöberg",
    "Simon Imark",
    "Axel Granqvist",
    "Isac Von Krusenstierna",
    "Henrik Johannesson",
    "Jens Rönnols",
    "Vojtech Kral",
    "Jerker Lysell",
    "Quentin Rauturier",
    "Joakim Svensk",
    "Olle Kalered",
    "Gustav Runefors",
    "Ludvig Ek",
    "Erik Herne",
    "Filip Ossiansson",
    "Jonas Gustafsson",
    "Rassmus Andersson",
    "Benjamin Näslund",
    "Jonatan Gustafsson",
    "Erik Andersson",
    "Filip Dahlgren",
    "Filip Trofast",
    "Jesper Svensk",
    "Erik Hannrup",
    "Johan Giberg",
    "Gustav Hindér",
    "Oliwer Lundberg",
    "Heino Ollin",
    "Johan Ek-Larsson",
    "Ville Johansson",
    "Simon Harden",
    "August Mollén",
    "Erik Classon",
    "Daniel Roos",
    "Filip Karlsson",
    "Viktor Skoog",
    "Axel Pannier",
    "Simon Wikström",
    "Emil Granqvist",
    "Kent Ohlsson",
    "Hugo Lillieström",
    "Oskar Sandberg",
    "Arvid Nord",
    "Leonas Mockunas",
    "Basile Basset",
    "Valter Pettersson",
    "Henrik Jonsson",
    "Daniel Hájek",
    "Fredrik Glännefors",
    "Johan Aronsson",
    "Algirdas Bartkevicius",
    "Simon Jakobsson",
    "Felix Späth",
    "Filip Grahn",
    "Rickard Börjesson",
    "Jonas Andersson",
    "Anton Gunnarsson",
    "Henrik Petrisi",
    "Robbin Kantarp",
    "Joar Hertin",
    "Pontus Petersson",
    "Florian Attinger",
    "Georg Groell",
    "Tim Johansson",
    "Fredrik Hamrefors",
    "Jimmy Larsson",
    "Matthias Groell",
    "Lukas Novak",
    "William Pommer",
    "Martin Ahlberger",
    "Oskar Spets Storhov",
    "Erik Berzell",
    "Leo Johansson",
    "Carl Carlsson"
]

sl_1_2023.d18result = [
    'Alva Björk',
    'Freja Hjerne',
    'Ella Laine',
    'Julia Forsgren',
    'Filippa Hjerne',
    'Lovisa Borg',
    'Tuva Östangård',
    'Signe Hördegårdh',
    'Elsa Hedin',
    'Tyra Larsson',
    'Sara Ohlin',
    'Filippa Braun',
    'Sandra Ling',
    'Lisa Östensson',
    'Yrsa Röjgård',
    'Stina Thern',
    'Elsa Brandt',
    'Tilda Sundkvist',
    'Alva Karlsson',
    'Ella Pettersson',
    'Julia Rosén',
    'Emma Zettervall',
    'Tilia Olsson',
    'Tuva Selin',
    'Amanda Cliffordson',
    'Maja Axelsson',
    'Annika Stamer',
    'Tuva Sirviö',
    'Elise Magnusson',
    'Emma Hasselström',
    'Maja Nordenfelt',
    'Stina Bygdén',
    'Alice Rytterstedt',
    'Agnes Johansson',
    'Ellen Wångberg Aneland',
    'Elsa Kaipe',
    'Annie Lund',
    'Malva Arvidsson',
    'Moa Bergqvist',
    'Maja Lundholm',
    'Tova Rangert',
    'Hedda Rosengren Svensson',
    'Moa Birkebæk',
    'Sigrid Ljunggren',
    'Wilma Reinholdsson',
    'Minna Palm',
    'Sofie Ettling',
    'Lina Ås',
    'Elsa Södervall',
    'Alva Engström',
    'Silje Ringstad',
    'Audrey Hansson',
    'Klara Zimmerman',
    'Hilda Mårsell',
    'Alice Johansson',
    'Ellen Lindfors',
    'Linn De Boussard',
    'Alva Hagelberg',
    'Maja Karlsson',
    'Emma Henriques',
    'Liv Pauler',
    'Hilda Petersson',
    'Wilma Kroksmyr',
    'Klara Hultberg',
    'Alice Wahlberg',
    'Alice Ljungberg',
    'Saga Källstrand',
    'Sigrid Forsman',
    'Klara Junegard',
    'Alva Forsman',
    'Ellen Thorsén',
    'Milla Forkéus',
    'Ingrid Johansson',
    'Vega Enell',
    'Moa Pihlström',
    'Ebba Ulvagården',
    'Emma Hallendal',
    'Filippa Guttke',
    'Linda Sahlin',
    'Johanna Louise Berg',
    'Lovisa Lindqvist',
    'Ida Körle',
    'Saga Palmertz',
    'Maja Torsein'
]

sl_1_2023.d20result = [
    "Eleonora Alinder",
    "Klara Borg",
    "Alice Ek",
    "Alma Svennerud",
    "Boglarka Czakó",
    "Elsa Sonesson",
    "Sabina Aumo",
    "Klara Åkerman Sjöström",
    "Ida Bengtsson",
    "Fredrika Nordquist",
    "Emma Emilsson",
    "Ebba Thern",
    "Ida Österberg",
    "Vendela Söderqvist",
    "Hanna Öberg",
    "Alva Svensk",
    "Tilda Palm",
    "Erika Åkesson",
    "Agnes Djurstedt",
    "Lisa Åkesson",
    "Karin Lindgren",
    "Doris Iko",
    "Nora Westerlund",
    "Ella Turesson",
    "Kerstin Ljungemyr",
    "Emma Almgren",
    "Alice Olvegård",
    "Ebba Ottosson",
    "Maja Ahlström",
    "Alice Johansson",
    "Linnea Lund",
    "Evelina Svensson Finndahl",
    "Vilma Engström",
    "Johanna Roos",
    "Vendela Rundström",
    "Elin Ladänges",
    "Tove Sjöberg",
    "Ingrid Mobråthen",
    "Emma Rindstig",
    "Matilda Aasa",
    "Liv Herne",
    "Ida Eskilsson",
    "Tove Wallerius",
    "Sara Åbom",
    "Jonna Lindblad",
    "Frida Jarding",
    "Tindra Jonsson",
    "Marie Bartosova",
    "Emma Norin",
    "Klara Kivijärvi",
    "Hanna Larsson",
    "Yelyzaveta Ostapenko",
    "Linnea Solvang Stagg",
    "Sigrid Carlsson",
    "Tilda Hagelberg",
    "Martina Niklasson",
    "Ebba Näsman",
    "Maja Bergqvist",
    "Maja Lindén",
    "Linn Andersson",
    "Lisa Swartz",
    "Thea Nordin Abaji",
    "Vendela Sturek",
    "Wilma Leickt",
    "Sara Sundqvist",
    "Rebecka Hasler",
    "Kajsa Heyden"
]

sl_1_2023.d21result = [
    "Karolin Ohlsson",
    "Andrea Svensson",
    "Johanna Ridefelt",
    "Elin Månsson",
    "Hilda Holmqvist Johansson",
    "Amanda Kleijn",
    "Josefin Tjernlund",
    "Lina Strand",
    "Tilde Backlund",
    "Alva Sonesson",
    "Ida Hylander",
    "Helena Karlsson",
    "Emma Bjessmo",
    "Alva Olsson",
    "Rebecka Heinrup",
    "Tilda Johansson",
    "Erica Edman",
    "Vilma Von Krusenstierna",
    "Susen Lösch",
    "Olivia Nilsson",
    "Johanna Källvik Leufvén",
    "Jennie Börjesson Eriksson",
    "Amanda Strandvall",
    "Ellinor Tjernlund",
    "Galina Ribediuc",
    "Frida Vikström",
    "Annick Meister",
    "Fanny Sundblad",
    "Rebecka Lindberg",
    "Johanna Börjesson Eriksson",
    "Anna Wehlin",
    "Lovisa Persson",
    "Emma Eriksson",
    "Fanny Asketun",
    "Signe Nilsson",
    "Laura King",
    "Alicia Lundgren",
    "Louise Lundgren",
    "Eef Van Dongen",
    "Johanna Engström",
    "Ella Sjöberg",
    "Linnea Claesdotter",
    "Gabriella Bergander",
    "Hanna Müller",
    "Madara Brice",
    "Sarah Persson",
    "Tereza Kosova",
    "Jeanette Jönsson Hellstadius",
    "Lucyna Wiktor",
    "Johanna Öberg",
    "Anna Hallmén",
    "Johanna Jonsson",
    "Lovisa Gustafsson",
    "Hanna Lagerberg",
    "Sandra Boström",
    "Sofia Wigle",
    "Josefine Klintberg",
    "Tilda Golsäter",
    "Filipa Rodrigues",
    "Kate Morrison",
    "Elin Nilsson",
    "Moa Alsiö",
    "Maja Mörth",
    "Elisabeth Ahlgren",
    "Matilda Lindh",
    "Klara Ljunggren",
    "Tove Ekström",
    "Markéta Pavlíková",
    "Jonna Fors",
    "Maja Porle",
    "Elin Rindstig",
    "Emma Beskow",
    "Magdalena Hajkova",
    "Linnéa Daniels",
    "Sara Kindlund",
    "Amelie Josefsson",
    "Alice Svensson Finndahl",
    "Anna Arvidsson",
    "Vilma Svantesson",
    "Emma Bengtsson",
    "Viktória Kostercová",
    "Tilda Andersson",
    "Elin Hugosson"
]



sl_2_2023 = cp.Competition("#2SL23")
sl_2_2023.date = datetime(2023, 4,16)
sl_2_2023.h18result = [
    "Hannes Mogensen",
    "Ludwig Rosén",
    "Odin Ek",
    "Max Österberg",
    "Oliver Håkansson",
    "Isak Eskilsson",
    "Noah Krikström",
    "Hannes Persson",
    "Albin Sundström",
    "Vidar Nettelmark",
    "Adam Sjööarv",
    "Ola Leire",
    "Linus Forsberg",
    "Hannes Lindqvist",
    "Kasparas Murėnas",
    "Axel Bratt",
    "Casper Blakskjær",
    "Anton Jonsson",
    "Otto Timby",
    "Alfred Kjellén",
    "Elis Peterson",
    "Niels Dalgaard",
    "William Oksvold",
    "Jonatan Anderson",
    "Felix Johnsson",
    "Edvin Halldin",
    "Elia Kämpe",
    "Marcus Lamm",
    "Olov Norin",  
    "Alfred Jeppsson",
    "Gustav Hellgren",
    "Wille Söderqvist",
    "Love Bylund",
    "Tim Martner",
    "Marcus Grunder",
    "Arvid Algers Omholt",
    "Mattia Corona",
    "Joel Wallner",
    "Simon Westh",
    "Erik Palm",
    "Emil Åberg",
    "Jacob Påledal",
    "Isak Skoglund",
    "Nils Swartz",
    "Olof Arevång",
    "Elias Westerbergh",
    "Carl Öberg",
    "Otto Nilsson",  
    "Filip Gummesson",
    "Viggo Holmberg",
    "Ian Johansson",
    "Ludvig Hasler",
    "Jens Fochsen",
    "Arvid Jonforsen",
    "Arvid Eriksson",
    "Elias Ljungdell",  
    "Wilmer Kempe",
    "Elmin Hovmöller",
    "David Böke",
    "Eddie Karlsson",
    "Erik Månsson",
    "Liam Hogedal",
    "Axel Trofast",
    "Eric Hasselström",
    "Mattias Larsson",
    "Viggo Wulff",
    "Jakob Omelchenko",
    "Olle Malmström",
    "Ludvig Eronn",
    "Felix Johansson",
    "Axel Hejdenberg",
    "Lukas Nilsson",
    "Edvin Wollbrand"
]

sl_2_2023.h20result = [
    "Lukas Larsson",
    "Albin Weiden",
    "Arvid Skepp",
    "William Sturesson",
    "Marcus Stenebo",
    "Henrik Lundfors",
    "Linus Wernström",
    "Edvin Forsberg",
    "Albin Gezelius",
    "Albin Warvelin",
    "Joel Golsäter",
    "Gunnar Fovaeus",
    "Edvin Hellsten",
    "Hugo Larsson",
    "Casper Skepp",
    "Isak Lundholm",
    "Hugo Kindborn",
    "Hugo Unosson",
    "Elias Nordberg",
    "Jesper Åkesson",
    "Mathias Barros-vallet",
    "Loke Hedberg",
    "Sverre Röjgård",
    "Viktor Sone",
    "Kasper Lagerström",
    "Sixten Slagbrand",
    "Hugo Örn",
    "Theo Lövdahl",
    "Leo Alvolin",
    "Oskar Vikström",
    "Emil Larsson",
    "Edvin Selin",
    "Hugo Persson",
    "Melker Åkesson",
    "Ludvig Lange",
    "John Kinnander",
    "Ludvig Hedström",
    "Mattias Öhlund",
    "Isak Gelius",
    "David Morén",
    "Rasmus Lindblom",
    "Florian Nagel",
    "Johan Årbrink",
    "Anders Skoglund",
    "Oskar Ådahl",
    "Esbjörn Montelius Risberg",
    "Oscar Wångberg Aneland",
    "Ludvig Karlqvist",
    "Isak Fransson",
    "Noel Helmersson",
    "Alfred Hallqvist",
    "Olle Thimberg",
    "Hannes Essunger",
    "Markus Ljungqvist",
    "Love Persson",
    "Anton Kruse",
    "Elis Forsberg Rundström",
    "Hjalmar Olsson",
    "Teo Struck",
    "Isak Andersson",
    "Viktor Fröberg",
    "Joel Holmberg",
    "Axel Eveborn",
    "Mattis Sandén",
    "Simon Bååth",
    "Johan Hansson",
    "Eric Johansson"
]

sl_2_2023.h21result = [
    "Anton Johansson", "Gustav Bergman", "Axel Elmblad", "Jerker Lysell",
    "Jonatan Gustafsson", "Simon Imark", "Isac Von Krusenstierna", "Jonas Gustafsson",
    "Simon Hector", "Joakim Svensk", "Jens Rönnols", "Oskar Sjöberg",
    "Filip Ossiansson", "Vojtech Kral", "Filip Dahlgren", "Gustav Runefors",
    "Nathan Marchand", "Filip Grahn", "Ville Johansson", "Rassmus Andersson",
    "Johan Ek-Larsson", "Algirdas Bartkevicius", "Erik Hannrup", "Simon Wikström",
    "Henrik Jonsson", "Benjamin Näslund", "Jesper Sjöblom", "Ludvig Ek",
    "Daniel Roos", "Matthias Groell", "Jesper Lidmar", "Basile Basset",
    "Quentin Rauturier", "Axel Granqvist", "Viktor Skoog", "Erik Andersson",
    "August Mollén", "Simon Jakobsson", "Axel Pannier", "Hugo Lillieström",
    "Daniel Bogren", "Oskar Sandberg", "Fredrik Glännefors", "Emil Björnlinger",
    "Jesper Svensk", "Daniel Hájek", "Gustav Hindér", "Tim Johansson",
    "Simon Harden", "Oliwer Lundberg", "Kent Ohlsson", "Arvid Nord",
    "Christian Michelsen", "Johan Giberg", "Jonas Andersson", "Leo Johansson",
    "Oskar Daniels", "Leonas Mockunas", "William Pommer", "Fredrik Hamrefors",
    "Georg Groell", "Jimmy Larsson", "Anton Silier", "Emil Öhlund",
    "Valter Pettersson", "Lukas Novak", "Emil Granqvist"
]

sl_2_2023.d18result = [
    "Alva Björk", "Freja Hjerne", "Elsa Hedin", "Tilda Sundkvist", "Tilia Olsson", "Lovisa Borg", "Elsa Kaipe",
    "Stina Thern", "Ella Pettersson", "Filippa Hjerne", "Lisa Östensson", "Signe Hördegårdh", "Tuva Östangård",
    "Ella Laine", "Julia Forsgren", "Silje Ringstad", "Tuva Selin", "Elise Magnusson", "Maja Axelsson",
    "Filippa Braun", "Annie Lund", "Hedda Rosengren Svensson", "Maja Karlsson", "Emma Zettervall", "Sara Ohlin",
    "Alva Karlsson", "Julia Rosén", "Tyra Larsson", "Tuva Sirviö", "Sigrid Ljunggren", "Emma Hasselström",
    "Stina Bygdén", "Malva Arvidsson", "Sofie Ettling", "Linn De Boussard", "Alice Ljungberg", "Sandra Ling",
    "Klara Zimmerman", "Maja Nordenfelt", "Amanda Cliffordson", "Johanna Louise Berg", "Annika Stamer",
    "Alice Rytterstedt", "Moa Bergqvist", "Filippa Guttke", "Alice Johansson", "Agnes Johansson", "Lina Ås",
    "Hilda Mårsell", "Saga Källstrand", "Audrey Hansson", "Klara Junegard", "Liv Pauler", "Minna Palm",
    "Klara Hultberg", "Wilma Reinholdsson", "Alice Wahlberg", "Maja Lundholm", "Ellen Thorsén", "Maja Falk",
    "Alva Engström", "Nova Sahlén", "Elsa Södervall", "Alva Forsman", "Lovisa Lindqvist", "Maja Lilja",
    "Hilda Petersson", "Sigrid Forsman", "Ellen Lindfors", "Milla Forkéus", "Saga Rydberg", "Lovisa Hallenek",
    "Mirjam Edin", "Line Nideborn", "Emily Kruys", "Kajsa Wallin", "Sofia Carlén"
]

sl_2_2023.d20result = [
    "Alma Svennerud", "Eleonora Alinder", "Sabina Aumo", "Klara Borg", "Elsa Sonesson",
    "Boglarka Czakó", "Lisa Åkesson", "Tilda Palm", "Alice Ek", "Erika Åkesson",
    "Alva Svensk", "Ida Österberg", "Vendela Söderqvist", "Ebba Thern", "Emma Emilsson",
    "Hanna Öberg", "Kerstin Ljungemyr", "Agnes Djurstedt", "Alice Johansson", "Doris Iko",
    "Klara Åkerman Sjöström", "Linnea Lund", "Nora Westerlund", "Vendela Rundström",
    "Emma Almgren", "Ida Eskilsson", "Karin Lindgren", "Ebba Ottosson", "Tindra Jonsson",
    "Elin Ladänges", "Vilma Engström", "Matilda Aasa", "Johanna Roos", "Jonna Lindblad",
    "Klara Kivijärvi", "Tove Sjöberg", "Ella Turesson", "Marie Bartosova", "Emma Rindstig",
    "Yelyzaveta Ostapenko", "Martina Niklasson", "Linnea Solvang Stagg", "Sara Åbom",
    "Sigrid Carlsson", "Tilda Hagelberg", "Maja Inghammar", "Maja Ahlström", "Maja Lindén",
    "Hanna Larsson", "Linn Andersson", "Rebecka Hasler", "Kajsa Heyden"
]

sl_2_2023.d21result = [
    "Karolin Ohlsson",
    "Elin Månsson",
    "Lina Strand",
    "Andrea Svensson",
    "Alva Olsson",
    "Amanda Kleijn",
    "Helena Karlsson",
    "Hilda Holmqvist Johansson",
    "Lena Eliasson-Lööf",
    "Alva Sonesson",
    "Tilda Johansson",
    "Josefin Tjernlund",
    "Frida Vikström",
    "Johanna Börjesson Eriksson",
    "Vilma Von Krusenstierna",
    "Susen Lösch",
    "Rebecka Heinrup",
    "Johanna Källvik Leufvén",
    "Ida Hylander",
    "Anna Wehlin",
    "Tilde Backlund",
    "Erica Edman",
    "Emma Bjessmo",
    "Olivia Nilsson",
    "Filipa Rodrigues",
    "Lovisa Persson",
    "Laura King",
    "Ellinor Tjernlund",
    "Fanny Sundblad",
    "Lucyna Wiktor",
    "Fanny Asketun",
    "Louise Lundgren",
    "Rebecka Lindberg",
    "Eef Van Dongen",
    "Hanna Müller",
    "Alicia Lundgren",
    "Jennie Börjesson Eriksson",
    "Annick Meister",
    "Signe Nilsson",
    "Hanna Lagerberg",
    "Moa Alsiö",
    "Tereza Kosova",
    "Ella Sjöberg",
    "Madara Brice",
    "Tilda Golsäter",
    "Anna Hallmén",
    "Sofia Wigle",
    "Elisabeth Ahlgren",
    "Emma Beskow",
    "Markéta Pavlíková",
    "Sandra Boström",
    "Elin Nilsson",
    "Maja Mörth",
    "Kate Morrison",
    "Amelie Josefsson",
    "Matilda Lindh",
    "Viktória Kostercová",
    "Lovisa Gustafsson",
    "Elin Hugosson"
]




sl_3_2023 = cp.Competition("#3SL23")
sl_3_2023.date = datetime(2023, 5,6)
sl_3_2023.h18result = [
    "Svante Selin",
    "Wilmer Selin",
    "Hannes Mogensen",
    "Albin Sundström",
    "Noah Krikström",
    "Axel Bratt",
    "Max Österberg",
    "Arvid Jonforsen",
    "Isak Eskilsson",
    "Ola Leire",
    "Alfred Kjellén",
    "Anton Jonsson",
    "Elis Peterson",
    "Casper Blakskjær",
    "Vidar Nettelmark",
    "Niels Dalgaard",
    "Tim Lundberg",
    "Victor Hörnquist",
    "Elia Kämpe",
    "Odin Ek",
    "Oliver Håkansson",
    "Hannes Persson",
    "Linus Forsberg",
    "Jacob Påledal",
    "Love Bylund",
    "Emil Åberg",
    "Hugo Sjölander",
    "Arvid Algers Omholt",
    "Gustav Hellgren",
    "Måns Bergqvist",
    "Joel Wallner",
    "Linus Nilsson",
    "Filip Gummesson",
    "Helmer Jöhnemark",
    "Ian Johansson",
    "Nils Swartz",
    "Niklas Erlandsson",
    "Elias Westerbergh",
    "Alfred Jeppsson",
    "Carl Öberg",
    "Viggo Wulff",
    "Olof Arevång",
    "Wille Söderqvist",
    "Tim Martner",
    "Jens Fochsen",
    "William Oksvold",
    "Otto Nilsson",
    "Kasparas Murėnas",
    "Ludvig Hasler",
    "Adam Sjööarv",
    "Marcus Grunder",
    "Harry Liderfelt",
    "Elmin Hovmöller",
    "Arvid Eriksson",
    "Emil Albinsson",
    "Edvin Halldin",
    "Axel Hejdenberg",
    "Mattias Larsson",
    "Jonathan Nilsson",
    "Felix Johnsson",
    "Viggo Holmberg",
    "Erik Palm",
    "Mattia Corona",
    "Liam Hogedal",
    "Felix Johansson",
    "Malte Albinsson",
    "Jonatan Anderson",
    "Erik Slätt",
    "Rasmus Lundström",
    "Viktor Wistrand",
    "Albin Skott",
    "Alexander Fedje",
    "Karl Aderstedt Althoff",
    "Elias Ljungdell",
    "Alvin Isenström"
]

sl_3_2023.h20result = [
    "Noel Braun",
    "Edvin Forsberg",
    "Linus Wernström",
    "Gunnar Fovaeus",
    "Joel Golsäter",
    "Hugo Larsson",
    "Edvin Hellsten",
    "Hugo Ericsson",
    "Marcus Stenebo",
    "Lukas Larsson",
    "Hugo Kindborn",
    "Viktor Gunnarsson",
    "Albin Warvelin",
    "Albin Gezelius",
    "Henrik Lundfors",
    "William Sturesson",
    "Casper Skepp",
    "Tobias Johansson",
    "Sixten Slagbrand",
    "Erik Bovallius",
    "Melker Åkesson",
    "Isak Gelius",
    "Johan Mårtensson",
    "Hugo Örn",
    "Anton Kruse",
    "Olle Thimberg",
    "Jesper Åkesson",
    "Mattias Öhlund",
    "Isak Lundholm",
    "Kasper Lagerström",
    "Albin Weiden",
    "Viktor Sone",
    "Rasmus Lindblom",
    "Ludvig Lange",
    "Johan Årbrink",
    "Elis Ivers",
    "Elis Forsberg Rundström",
    "Theo Lövdahl",
    "Ludvig Hedström",
    "Hjalmar Olsson",
    "Emil Larsson",
    "Esbjörn Montelius Risberg",
    "Alfred Hallqvist",
    "Melker Larsson",
    "Simon Claesson",
    "Oskar Ådahl",
    "Adrian Sjödin",
    "Arvid Skepp",
    "Edvin Selin",
    "Oskar Vikström",
    "Alfred Johansson",
    "Hugo Persson",
    "Ludvig Karlqvist",
    "Marcus Ekman",
    "Isak Fransson",
    "Olle Erlandsson",
    "Carl Stadig",
    "Simon Karlsson Holmer",
    "Viktor Fröberg",
    "Johan Hansson",
    "Love Persson",
    "Isak Andersson",
    "Mattis Sandén",
    "Oscar Wångberg Aneland",
    "John Kinnander",
    "Anton Uller",
    "Noel Helmersson",
    "Oscar Olin",
    "Loke Hedberg",
    "Oskar Ericsson"
]

sl_3_2023.h21result = [
    "Gustav Bergman",
    "Axel Elmblad",
    "Martin Regborn",
    "Simon Hector",
    "Jonatan Gustafsson",
    "Eskil Kinneberg",
    "Axel Granqvist",
    "Jonas Gustafsson",
    "Rassmus Andersson",
    "Erik Herne",
    "Emil Auselius",
    "Viktor Svensk",
    "Simon Imark",
    "Jesper Svensk",
    "Joakim Svensk",
    "Ludvig Ek",
    "Olle Kalered",
    "Erik Andersson",
    "Henrik Johannesson",
    "Erik Hannrup",
    "Gustav Runefors",
    "Johan Ek-Larsson",
    "Simon Jakobsson",
    "Filip Grahn",
    "Jacob Steinthal",
    "Ville Johansson",
    "Henrik Jonsson",
    "Rasmus Møller Jess",
    "Fredrik Glännefors",
    "Simon Wikström",
    "August Mollén",
    "Emil Granqvist",
    "Benjamin Näslund",
    "Daniel Roos",
    "Andreas Uller",
    "Johan Runesson",
    "Filip Trofast",
    "Erik Berzell",
    "Heino Ollin",
    "Axel Wrådhe",
    "Anton Forsberg",
    "Oliwer Lundberg",
    "Vegard Kittilsen",
    "Artem Panchenko",
    "Marcus Millegård",
    "Filip Dahlgren",
    "Arvid Nord",
    "Kornelius Kriszat-Løvfald",
    "Oskar Sandberg",
    "Ludvig Åhlund",
    "Jesper Sjöblom",
    "Filip Ossiansson",
    "Algirdas Bartkevicius",
    "Antoine Becaert",
    "Viktor Skoog",
    "Jimmy Larsson",
    "Quentin Rauturier",
    "Jesper Johansson",
    "Valter Pettersson",
    "Leo Johansson",
    "Fredrik Hamrefors",
    "Mattia Debertolis",
    "Robbin Kantarp",
    "Axel Olsson",
    "Kent Ohlsson",
    "Rasmus Svantesson",
    "Joar Hertin",
    "Jens Rönnols",
    "Martin Ahlberger",
    "Hugo Lillieström",
    "Rickard Börjesson",
    "Jonas Andersson",
    "Ludvig Eriksson",
    "Johan Aronsson",
    "Linus Lundberg",
    "William Pommer",
    "Henrik Petrisi",
    "Erik Barr Zeilon",
    "Carl Carlsson",
    "Filip Karlsson"
]

sl_3_2023.d18result = [
    "Freja Hjerne", "Alva Björk", "Tilia Olsson", "Stina Thern", "Tuva Östangård",
    "Lovisa Borg", "Elsa Hedin", "Signe Hördegårdh", "Tuva Selin", "Filippa Braun",
    "Lisa Östensson", "Amanda Cliffordson", "Maja Axelsson", "Tyra Larsson",
    "Hedda Rosengren Svensson", "Yrsa Röjgård", "Ellen Wångberg Aneland",
    "Tuva Sirviö", "Alva Karlsson", "Alice Ljungberg", "Tilda Sundkvist",
    "Stina Bygdén", "Sandra Ling", "Filippa Guttke", "Ella Laine", "Annika Stamer",
    "Emma Henriques", "Maja Nordenfelt", "Moa Bergqvist", "Alice Rytterstedt",
    "Sigrid Ljunggren", "Elise Magnusson", "Emma Zettervall", "Emma Hasselström",
    "Sara Ohlin", "Sofie Ettling", "Maja Lundholm", "Wilma Reinholdsson",
    "Ida Körle", "Nelly Mårtensson", "Liv Pauler", "Malva Arvidsson",
    "Agnes Johansson", "Maja Lilja", "Beatrice Österberg", "Irma Berg",
    "Silje Ringstad", "Elsa Södervall", "Ella Pettersson", "Alva Hagelberg",
    "Alice Johansson", "Ellen Thorsén", "Lina Ås", "Annie Lund",
    "Ingrid Johansson", "Fanny Hansson", "Moa Birkebæk", "Alice Wahlberg",
    "Alva Forsman", "Julia Forsgren", "Johanna Louise Berg", "Moa Pihlström",
    "Klara Hultberg", "Hilda Mårsell", "Filippa Hjerne", "Emma Hallendal",
    "Ellen Lindfors", "Julia Gustafsson", "Linn De Boussard", "Sofie Karlsson Holmer",
    "Ebba Samuelsson", "Maja Torsein", "Maja Karlsson", "Klara Junegard",
    "Milla Forkéus", "Malin Strömqvist", "Sigrid Forsman", "Helena Eriksson"
]

sl_3_2023.d20result = [
    "Boglarka Czakó",
    "Alice Ek",
    "Ida Bengtsson",
    "Tilda Palm",
    "Elsa Sonesson",
    "Hanna Öberg",
    "Alva Svensk",
    "Ida Österberg",
    "Amanda Granqvist",
    "Kerstin Ljungemyr",
    "Agnes Djurstedt",
    "Fredrika Nordquist",
    "Karin Lindgren",
    "Klara Åkerman Sjöström",
    "Hanna Jonsell",
    "Alma Svennerud",
    "Klara Borg",
    "Ebba Thern",
    "Cornelia Kindlund",
    "Vendela Söderqvist",
    "Ella Turesson",
    "Smilla Mogensen",
    "Alice Olvegård",
    "Alice Johansson",
    "Ida Eskilsson",
    "Vendela Rundström",
    "Ebba Ottosson",
    "Tove Wallerius",
    "Doris Iko",
    "Emma Almgren",
    "Nora Westerlund",
    "Elina Reinholdsson",
    "Ebba Näsman",
    "Emma Rindstig",
    "Evelina Svensson Finndahl",
    "Maja Ahlström",
    "Sigrid Carlsson",
    "Ellen Pelander",
    "Thea Nordin Abaji",
    "Matilda Aasa",
    "Tindra Jonsson",
    "Tilda Hagelberg",
    "Yelyzaveta Ostapenko",
    "Tuva Nylund",
    "Emma Westerlund",
    "Saga Mattsson",
    "Emma Norin",
    "Linnea Lund",
    "Sara Sundqvist",
    "Wilma Leickt",
    "Eline Ericsson",
    "Olga Rindeskog",
    "Maja Bergqvist",
    "Karolina Andersson",
    "Amanda Hall",
    "Marie Bartosova",
    "Maja Inghammar",
    "Agnes Wallin",
    "Hanna Larsson",
    "Clara Svensson",
    "Rebecka Hasler"
]

sl_3_2023.d21result = [
    "Andrea Svensson",
    "Lisa Risby",
    "Josefin Tjernlund",
    "Elin Månsson",
    "Amanda Kleijn",
    "Helena Karlsson",
    "Alva Sonesson",
    "Susen Lösch",
    "Tilde Backlund",
    "Ellinor Tjernlund",
    "Johanna Källvik Leufvén",
    "Hilda Holmqvist Johansson",
    "Alva Olsson",
    "Jennie Börjesson Eriksson",
    "Erica Edman",
    "Olivia Nilsson",
    "Lena Eliasson-Lööf",
    "Emma Bjessmo",
    "Emma Ling",
    "Tilda Östberg",
    "Frida Vikström",
    "Galina Ribediuc",
    "Frida Sandberg",
    "Fanny Asketun",
    "Rebecka Heinrup",
    "Alice Hugosson",
    "Louise Lundgren",
    "Rebecka Lindberg",
    "Ella Sjöberg",
    "Matilda Eriksson",
    "Julia Davidsson",
    "Johanna Öberg",
    "Corina Hüni",
    "Amanda Strandvall",
    "Emma Eriksson",
    "Line Cederberg",
    "Tova Olsson",
    "Sarah Persson",
    "Anna Wehlin",
    "Zsófia Sárközy",
    "Linda Lindkvist",
    "Lilly Graber",
    "Ida Hylander",
    "Jeanette Jönsson Hellstadius",
    "Fanny Sundblad",
    "Miri Thrane Ødum",
    "Johanna Sjölund",
    "Marianne Haug",
    "Agnes Nørgård Kracht",
    "Jannie Hagård",
    "Laura King",
    "Anna Hallmén",
    "Elin Nilsson",
    "Vilma Von Krusenstierna",
    "Signe Nilsson",
    "Yevheniia Veremeienko",
    "Sanna Skoog",
    "Elin Rindstig",
    "Kate Morrison",
    "Johanna Börjesson Eriksson",
    "Hanna Lagerberg",
    "Pim Hedberg",
    "Lisa Andersson",
    "Cornelia Ivarsson",
    "Tilda Golsäter",
    "Lovisa Persson",
    "Alicia Lundgren",
    "Emma Beskow",
    "Matilda Martinsson",
    "Filipa Rodrigues",
    "Eef Van Dongen"
]



sl_4_2023 = cp.Competition("#4SL23")
sl_4_2023.date = datetime(2023, 5,7)
sl_4_2023.h18result = [
    'Wilmer Selin',
    'Svante Selin',
    'Ola Leire',
    'Odin Ek',
    'Ludwig Rosén',
    'Anton Jonsson',
    'Isak Eskilsson',
    'Axel Bratt',
    'Hannes Persson',
    'Noah Krikström',
    'Alfred Kjellén',
    'Linus Forsberg',
    'Vidar Nettelmark',
    'Victor Hörnquist',
    'Gustav Hellgren',
    'Elis Peterson',
    'Tim Lundberg',
    'Kasparas Murėnas',
    'Felix Johnsson',
    'Joel Wallner',
    'Niels Dalgaard',
    'Elia Kämpe',
    'Adam Sjööarv',
    'Jonatan Anderson',
    'Arvid Algers Omholt',
    'Max Österberg',
    'Måns Bergqvist',
    'Simon Westh',
    'Albin Sundström',
    'Olof Arevång',
    'Tim Martner',
    'Isak Skoglund',
    'Harry Liderfelt',
    'Elias Westerbergh',
    'Alfred Jeppsson',
    'Viggo Wulff',
    'Emil Åberg',
    'Erik Palm',
    'Arvid Jonforsen',
    'Oliver Liwång',
    'Axel Hejdenberg',
    'Helmer Jöhnemark',
    'Hampus Sundberg',
    'Viggo Holmberg',
    'Axel Trofast',
    'Jens Fochsen',
    'Carl Öberg',
    'Filip Gummesson',
    'Nils Swartz',
    'Arvid Eriksson',
    'Andrei Kuzmin',
    'Liam Hogedal',
    'Otto Nilsson',
    'Felix Johansson',
    'Niklas Erlandsson',
    'Erik Lundquist',
    'Ludvig Hasler',
    'Wille Söderqvist',
    'Ivar Henriksson',
    'Marcus Grunder',
    'Jacob Påledal',
    'Elias Ljungdell',
    'William Oksvold',
    'Karl Aderstedt Althoff',
    'Mattias Larsson',
    'Axel Rydgren',
    'Viktor Wistrand',
    'Ian Johansson',
    'Edvin Wollbrand',
    'Albin Skott'
]

sl_4_2023.h20result = [
    "Noel Braun",
    "Arvid Skepp",
    "Linus Wernström",
    "Albin Warvelin",
    "Hugo Larsson",
    "Marcus Stenebo",
    "Edvin Hellsten",
    "Albin Weiden",
    "Hugo Kindborn",
    "Hugo Ericsson",
    "Gunnar Fovaeus",
    "Loke Hedberg",
    "Casper Skepp",
    "Lukas Larsson",
    "Hugo Örn",
    "Jesper Åkesson",
    "Albin Gezelius",
    "William Sturesson",
    "Isak Gelius",
    "Sverre Röjgård",
    "Joel Golsäter",
    "Henrik Lundfors",
    "Erik Bovallius",
    "Theo Lövdahl",
    "Alfred Hallqvist",
    "Oskar Vikström",
    "Olle Thimberg",
    "Adrian Sjödin",
    "Kasper Lagerström",
    "Viktor Sone",
    "Isak Lundholm",
    "Melker Larsson",
    "Tobias Johansson",
    "Esbjörn Montelius Risberg",
    "Edvin Selin",
    "Sixten Slagbrand",
    "Mattias Öhlund",
    "Oskar Ådahl",
    "Ludvig Hedström",
    "Elis Ivers",
    "Ludvig Karlqvist",
    "Noel Helmersson",
    "Simon Claesson",
    "Isak Andersson",
    "Elis Forsberg Rundström",
    "Hugo Persson",
    "Viktor Fröberg",
    "Alfred Johansson",
    "Rasmus Lindblom",
    "Marcus Ekman",
    "Hjalmar Olsson",
    "Carl Stadig",
    "Love Persson",
    "Olle Erlandsson",
    "Simon Karlsson Holmer",
    "Johan Hansson",
    "Isak Fransson",
    "Oscar Wångberg Aneland",
    "Oscar Olin",
    "Mattis Sandén"
]

sl_4_2023.h21result = [
    "Gustav Bergman", "Martin Regborn", "Viktor Svensk", "Rassmus Andersson",
    "Axel Elmblad", "Joakim Svensk", "Axel Granqvist", "Heino Ollin",
    "Henrik Johannesson", "Jens Rönnols", "Jonas Gustafsson", "Simon Hector",
    "Simon Imark", "Johan Giberg", "Filip Dahlgren", "Olle Kalered",
    "Jesper Svensk", "Filip Ossiansson", "Ville Johansson", "Johan Ek-Larsson",
    "Marcus Millegård", "Filip Grahn", "Emil Auselius", "Daniel Roos",
    "Ludvig Ek", "Erik Hannrup", "Quentin Rauturier", "Gustav Runefors",
    "Fredrik Glännefors", "Jonatan Gustafsson", "August Mollén", "Filip Trofast",
    "Erik Herne", "Oliwer Lundberg", "Emil Björnlinger", "Erik Andersson",
    "Jesper Sjöblom", "Hugo Mattsson", "Henrik Jonsson", "Hugo Lillieström",
    "Daniel Hájek", "Jesper Lidmar", "Simon Harden", "Andreas Uller",
    "Anton Forsberg", "Benjamin Näslund", "Simon Wikström", "Jesper Johansson",
    "Joar Hertin", "Leo Johansson", "Mattia Debertolis", "Kent Ohlsson",
    "Arvid Nord", "Leonas Mockunas", "Artem Panchenko", "Viktor Skoog",
    "Rickard Börjesson", "Fredrik Hamrefors", "Axel Wrådhe", "Jimmy Larsson",
    "Robbin Kantarp", "Johan Runesson", "Rasmus Pettersson", "Valter Pettersson",
    "Olof Skoglund", "Axel Olsson", "Daniel Bogren"
]

sl_4_2023.d18result = [
    "Freja Hjerne",
    "Ella Laine",
    "Filippa Hjerne",
    "Tilia Olsson",
    "Stina Thern",
    "Elsa Hedin",
    "Silje Ringstad",
    "Lovisa Borg",
    "Julia Forsgren",
    "Alva Björk",
    "Elise Magnusson",
    "Annika Stamer",
    "Sara Ohlin",
    "Tilda Sundkvist",
    "Irma Berg",
    "Hedda Rosengren Svensson",
    "Tuva Selin",
    "Tuva Sirviö",
    "Tuva Östangård",
    "Filippa Braun",
    "Alva Karlsson",
    "Alice Ljungberg",
    "Lisa Östensson",
    "Amanda Cliffordson",
    "Annie Lund",
    "Tyra Larsson",
    "Liv Pauler",
    "Sofie Ettling",
    "Emma Zettervall",
    "Signe Hördegårdh",
    "Klara Zimmerman",
    "Maja Karlsson",
    "Malva Arvidsson",
    "Emma Hasselström",
    "Moa Bergqvist",
    "Maja Nordenfelt",
    "Sandra Ling",
    "Maja Lundholm",
    "Sigrid Ljunggren",
    "Klara Junegard",
    "Stina Bygdén",
    "Ida Körle",
    "Alva Hagelberg",
    "Ella Pettersson",
    "Milla Forkéus",
    "Elsa Södervall",
    "Alice Rytterstedt",
    "Linn De Boussard",
    "Wilma Reinholdsson",
    "Ellen Wångberg Aneland",
    "Emma Henriques",
    "Ellen Lindfors",
    "Lina Ås",
    "Hilda Mårsell",
    "Filippa Guttke",
    "Emma Hallendal",
    "Nova Sahlén",
    "Nelly Mårtensson",
    "Ida Palm",
    "Emma Christiansson",
    "Johanna Louise Berg",
    "Sigrid Forsman",
    "Alice Johansson",
    "Alva Forsman",
    "Ingrid Johansson",
    "Klara Hultberg",
    "Julia Gustafsson",
    "Molly Gelius",
    "Fanny Hansson",
    "Alva Lidström Lauri",
    "Kajsa Wallin",
    "Maja Axelsson",
    "Tilde Mansén",
    "Emily Kruys",
    "Alice Wahlberg"
]

sl_4_2023.d20result = [
    "Alma Svennerud",
    "Boglarka Czakó",
    "Amanda Granqvist",
    "Tilda Palm",
    "Klara Borg",
    "Alice Ek",
    "Alva Svensk",
    "Hanna Jonsell",
    "Hanna Öberg",
    "Elsa Sonesson",
    "Vendela Söderqvist",
    "Kerstin Ljungemyr",
    "Ebba Thern",
    "Agnes Djurstedt",
    "Linnea Lund",
    "Klara Åkerman Sjöström",
    "Cornelia Kindlund",
    "Ida Österberg",
    "Tove Wallerius",
    "Evelina Svensson Finndahl",
    "Ebba Ottosson",
    "Emma Almgren",
    "Smilla Mogensen",
    "Ida Bengtsson",
    "Vendela Rundström",
    "Ida Eskilsson",
    "Emma Rindstig",
    "Ebba Näsman",
    "Elina Reinholdsson",
    "Maja Ahlström",
    "Ella Turesson",
    "Olga Rindeskog",
    "Marie Bartosova",
    "Fredrika Nordquist",
    "Alice Olvegård",
    "Tindra Jonsson",
    "Sigrid Carlsson",
    "Tilda Hagelberg",
    "Alice Johansson",
    "Alicia Bergkvist",
    "Jonna Lindblad",
    "Yelyzaveta Ostapenko",
    "Hanna Larsson",
    "Eline Ericsson",
    "Matilda Aasa",
    "Thea Nordin Abaji",
    "Emma Norin",
    "Rebecka Hasler",
    "Saga Mattsson"
]

sl_4_2023.d21result = [
    "Andrea Svensson",
    "Miri Thrane Ødum",
    "Elin Månsson",
    "Helena Karlsson",
    "Amanda Kleijn",
    "Alva Olsson",
    "Tilda Östberg",
    "Frida Vikström",
    "Josefin Tjernlund",
    "Tilde Backlund",
    "Line Cederberg",
    "Zsófia Sárközy",
    "Lisa Risby",
    "Alice Hugosson",
    "Rebecka Heinrup",
    "Alva Sonesson",
    "Olivia Nilsson",
    "Emma Bjessmo",
    "Erica Edman",
    "Johanna Börjesson Eriksson",
    "Hilda Holmqvist Johansson",
    "Ellinor Tjernlund",
    "Johanna Källvik Leufvén",
    "Lovisa Persson",
    "Susen Lösch",
    "Eef Van Dongen",
    "Lena Eliasson-Lööf",
    "Filipa Rodrigues",
    "Louise Lundgren",
    "Galina Ribediuc",
    "Lilly Graber",
    "Emma Ling",
    "Jennie Börjesson Eriksson",
    "Matilda Eriksson",
    "Anna Wehlin",
    "Agnes Nørgård Kracht",
    "Rebecka Lindberg",
    "Signe Nilsson",
    "Lucyna Wiktor",
    "Linnea Claesdotter",
    "Jannie Hagård",
    "Alicia Lundgren",
    "Laura King",
    "Anna Hallmén",
    "Amanda Strandvall",
    "Sandra Boström",
    "Corina Hüni",
    "Fanny Sundblad",
    "Frida Sandberg",
    "Johanna Sjölund",
    "Yevheniia Veremeienko",
    "Jenny Lindberg",
    "Ida Hylander",
    "Leonore Winkler",
    "Ellinor Almkvist",
    "Pim Hedberg",
    "Sanna Skoog",
    "Elisabeth Ahlgren",
    "Kate Morrison",
    "Elin Nilsson",
    "Hedwig Haas",
    "Lovisa Gustafsson"
]



all_competitions = [sl_1_2023, sl_2_2023, sl_3_2023, sl_4_2023, lång_sm_2023, medel_sm_2023]
#all_competitions = [lång_sm_2023, medel_sm_2023]
